/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JMenuItem;

/**
 *
 * @author Lenovo
 */
public class FrameServer extends javax.swing.JFrame {

    /**
     * Creates new form FrameServer
     */
    public FrameServer() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public JMenuItem getJmenuServerPokreni() {
        return jmenuServerPokreni;
    }

    public JMenuItem getJmenuServerZaustavi() {
        return jmenuServerZaustavi;
    }

    public JMenuItem getJmenuKonfiguracijaIzmeni() {
        return jmenuKonfiguracijaIzmeni;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuServer = new javax.swing.JMenu();
        jmenuServerPokreni = new javax.swing.JMenuItem();
        jmenuServerZaustavi = new javax.swing.JMenuItem();
        jmenuKonfiguracija = new javax.swing.JMenu();
        jmenuKonfiguracijaIzmeni = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmenuServer.setText("Server");

        jmenuServerPokreni.setText("Pokreni");
        jmenuServer.add(jmenuServerPokreni);

        jmenuServerZaustavi.setText("Zaustavi");
        jmenuServer.add(jmenuServerZaustavi);

        jMenuBar1.add(jmenuServer);

        jmenuKonfiguracija.setText("Konfiguracija");

        jmenuKonfiguracijaIzmeni.setText("Izmeni");
        jmenuKonfiguracija.add(jmenuKonfiguracijaIzmeni);

        jMenuBar1.add(jmenuKonfiguracija);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmenuKonfiguracija;
    private javax.swing.JMenuItem jmenuKonfiguracijaIzmeni;
    private javax.swing.JMenu jmenuServer;
    private javax.swing.JMenuItem jmenuServerPokreni;
    private javax.swing.JMenuItem jmenuServerZaustavi;
    // End of variables declaration//GEN-END:variables
}
