/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author Lenovo
 */
public class FrameGlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form FrameGlavnaForma
     */
    public FrameGlavnaForma() {
        initComponents();
    }
    
    public JMenu getjMenuIznajmljivanje() {
        return jMenuIznajmljivanje;
    }

    public JMenuItem getjMenuIznajmljivanjePretraga() {
        return jMenuIznajmljivanjePretraga;
    }

    public JMenuItem getjMenuIznajmljivanjeUnos() {
        return jMenuIznajmljivanjeUnos;
    }

    public JMenu getjMenuKlijent() {
        return jMenuKlijent;
    }

    public JMenuItem getjMenuKlijentPretraga() {
        return jMenuKlijentPretraga;
    }

    public JMenuItem getjMenuKlijentUnos() {
        return jMenuKlijentUnos;
    }

    public JMenu getjMenuAutomobil() {
        return jMenuAutomobil;
    }

    public JMenuItem getjMenuAutomobilPretraga() {
        return jMenuAutomobilPretraga;
    }

    public JMenuItem getjMenuAutomobilUnos() {
        return jMenuAutomobilUnos;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuKlijent = new javax.swing.JMenu();
        jMenuKlijentUnos = new javax.swing.JMenuItem();
        jMenuKlijentPretraga = new javax.swing.JMenuItem();
        jMenuAutomobil = new javax.swing.JMenu();
        jMenuAutomobilUnos = new javax.swing.JMenuItem();
        jMenuAutomobilPretraga = new javax.swing.JMenuItem();
        jMenuIznajmljivanje = new javax.swing.JMenu();
        jMenuIznajmljivanjeUnos = new javax.swing.JMenuItem();
        jMenuIznajmljivanjePretraga = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuKlijent.setText("Klijent");

        jMenuKlijentUnos.setText("Unos");
        jMenuKlijent.add(jMenuKlijentUnos);

        jMenuKlijentPretraga.setText("Pretraga");
        jMenuKlijent.add(jMenuKlijentPretraga);

        jMenuBar1.add(jMenuKlijent);

        jMenuAutomobil.setText("Automobil");

        jMenuAutomobilUnos.setText("Unos");
        jMenuAutomobil.add(jMenuAutomobilUnos);

        jMenuAutomobilPretraga.setText("Pretraga");
        jMenuAutomobil.add(jMenuAutomobilPretraga);

        jMenuBar1.add(jMenuAutomobil);

        jMenuIznajmljivanje.setText("Iznajmljivanje");

        jMenuIznajmljivanjeUnos.setText("Unos");
        jMenuIznajmljivanje.add(jMenuIznajmljivanjeUnos);

        jMenuIznajmljivanjePretraga.setText("Pretraga");
        jMenuIznajmljivanje.add(jMenuIznajmljivanjePretraga);

        jMenuBar1.add(jMenuIznajmljivanje);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAutomobil;
    private javax.swing.JMenuItem jMenuAutomobilPretraga;
    private javax.swing.JMenuItem jMenuAutomobilUnos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuIznajmljivanje;
    private javax.swing.JMenuItem jMenuIznajmljivanjePretraga;
    private javax.swing.JMenuItem jMenuIznajmljivanjeUnos;
    private javax.swing.JMenu jMenuKlijent;
    private javax.swing.JMenuItem jMenuKlijentPretraga;
    private javax.swing.JMenuItem jMenuKlijentUnos;
    // End of variables declaration//GEN-END:variables
}
