/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Lenovo
 */
public class PanelObrisiIznajmljivanje extends javax.swing.JPanel {

    /**
     * Creates new form PanelObrisiIznajmljivanje
     */
    public PanelObrisiIznajmljivanje() {
        initComponents();
    }

     public JButton getBtnDa() {
        return btnDa;
    }

    public JButton getBtnNe() {
        return btnNe;
    }

    public JLabel getLblPitanje() {
        return lblPitanje;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPitanje = new javax.swing.JLabel();
        btnDa = new javax.swing.JButton();
        btnNe = new javax.swing.JButton();

        lblPitanje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPitanje.setText("Da li ste sigurni da želite da obrišete? ");

        btnDa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDa.setText("Da");

        btnNe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNe.setText("Ne");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(lblPitanje, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btnDa)
                .addGap(74, 74, 74)
                .addComponent(btnNe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblPitanje)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDa)
                    .addComponent(btnNe))
                .addContainerGap(167, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDa;
    private javax.swing.JButton btnNe;
    private javax.swing.JLabel lblPitanje;
    // End of variables declaration//GEN-END:variables
}
